apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: democratic-heron-nodejs
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/private_repo:ec0cedc422a17c55744eda4762f410a95c7a02cb@sha256:86b55a5f20aad7a5d9d0f78e86cc9a327d53eb73d3e5b3edf989a341b7c92cb9
        name: container-image  
