apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: democratic-heron-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: democratic-heron-nodejs 
  name: democratic-heron-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: democratic-heron-nodejs 
